-- MySQL Script generated by MySQL Workbench
-- lun 24 mar 2025 20:29:58 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`languages` (
  `id_language` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `culture` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_language`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`countries` (
  `country_id` INT NOT NULL,
  `name` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id_roles` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_roles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_roles` (
  `id_role` INT NOT NULL,
  `last_update` DATETIME NOT NULL DEFAULT NOW(),
  `user_name` VARCHAR(45) NOT NULL,
  `checksum` VARBINARY(255) NOT NULL,
  `enabled` BIT(1) NULL DEFAULT 1,
  `deleted` BIT(1) NULL DEFAULT 0,
  `id_roles` INT NOT NULL,
  PRIMARY KEY (`id_role`),
  INDEX `fk_user_roles_roles1_idx` (`id_roles` ASC) VISIBLE,
  CONSTRAINT `fk_user_roles_roles1`
    FOREIGN KEY (`id_roles`)
    REFERENCES `mydb`.`roles` (`id_roles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id_user` INT NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `cedula` VARCHAR(30) NOT NULL,
  `contraseña` VARBINARY(170) NOT NULL,
  `email` VARCHAR(180) NOT NULL,
  `id_language` INT NULL,
  `country_id` INT NULL,
  `id_role` INT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_users_languages1_idx` (`id_language` ASC) VISIBLE,
  INDEX `fk_users_countries1_idx` (`country_id` ASC) VISIBLE,
  INDEX `fk_users_user_roles1_idx` (`id_role` ASC) VISIBLE,
  CONSTRAINT `fk_users_languages1`
    FOREIGN KEY (`id_language`)
    REFERENCES `mydb`.`languages` (`id_language`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`countries` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_user_roles1`
    FOREIGN KEY (`id_role`)
    REFERENCES `mydb`.`user_roles` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`type_service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`type_service` (
  `typeservi_id` INT NOT NULL,
  `nametype` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`typeservi_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`company_provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company_provider` (
  `company_id` INT NOT NULL,
  `namecompany` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`company_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`services_available`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`services_available` (
  `serviavailable_id` INT NOT NULL,
  `nameservi` VARCHAR(45) NOT NULL,
  `type_service_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`serviavailable_id`),
  INDEX `fk_pay_servi_available_pay_typeservi1_idx` (`type_service_id` ASC) VISIBLE,
  INDEX `fk_pay_servi_available_pay_company1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_pay_servi_available_pay_typeservi1`
    FOREIGN KEY (`type_service_id`)
    REFERENCES `mydb`.`type_service` (`typeservi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pay_servi_available_pay_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `mydb`.`company_provider` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servi_suscritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servi_suscritos` (
  `id_servisuscritos` INT NOT NULL,
  `nombreservidelusuario` VARCHAR(45) NOT NULL,
  `contrato` VARCHAR(45) NOT NULL,
  `enabled` BIT(1) NOT NULL DEFAULT 1,
  `servi_available_id` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_servisuscritos`),
  INDEX `fk_pay_servi_suscritos_pay_servi_available1_idx` (`servi_available_id` ASC) VISIBLE,
  INDEX `fk_servi_suscritos_users1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_pay_servi_suscritos_pay_servi_available1`
    FOREIGN KEY (`servi_available_id`)
    REFERENCES `mydb`.`services_available` (`serviavailable_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servi_suscritos_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permission_modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permission_modules` (
  `id_module` TINYINT(8) NOT NULL,
  `name` VARCHAR(40) NULL,
  PRIMARY KEY (`id_module`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permissions` (
  `id_permission` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `permission_modules_id_module` TINYINT(8) NOT NULL,
  PRIMARY KEY (`id_permission`),
  INDEX `fk_permissions_permission_modules1_idx` (`permission_modules_id_module` ASC) VISIBLE,
  CONSTRAINT `fk_permissions_permission_modules1`
    FOREIGN KEY (`permission_modules_id_module`)
    REFERENCES `mydb`.`permission_modules` (`id_module`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role_permissions` (
  `id_permission` INT NOT NULL,
  `enabled` BIT(1) NOT NULL DEFAULT 1,
  `deleted` BIT(1) NOT NULL DEFAULT 0,
  `last_update` DATETIME NULL DEFAULT NOW(),
  `roles_id_roles` INT NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `checksum` VARBINARY(255) NOT NULL,
  `permissions_id_permission` INT NOT NULL,
  PRIMARY KEY (`id_permission`),
  INDEX `fk_role_permissions_roles1_idx` (`roles_id_roles` ASC) VISIBLE,
  INDEX `fk_role_permissions_permissions1_idx` (`permissions_id_permission` ASC) VISIBLE,
  CONSTRAINT `fk_role_permissions_roles1`
    FOREIGN KEY (`roles_id_roles`)
    REFERENCES `mydb`.`roles` (`id_roles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_permissions_permissions1`
    FOREIGN KEY (`permissions_id_permission`)
    REFERENCES `mydb`.`permissions` (`id_permission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_suscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_suscription` (
  `suscription_id` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `logo_url` VARCHAR(200) NOT NULL,
  `startdate` DATETIME NOT NULL,
  `enddate` DATETIME NULL,
  `deleted` BIT(1) NOT NULL DEFAULT 0,
  `enabled` BIT(1) NOT NULL DEFAULT 1,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`suscription_id`),
  INDEX `fk_users_suscription_users1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_users_suscription_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaction_receipt_mediatype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transaction_receipt_mediatype` (
  `id_transaction_receipt_mediatype` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `player_impl` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_transaction_receipt_mediatype`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaction_receipt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transaction_receipt` (
  `id_transaction_receipt` INT NOT NULL AUTO_INCREMENT,
  `pdfURL` VARCHAR(200) NOT NULL,
  `deleted` BIT(1) NOT NULL DEFAULT 0,
  `id_transaction_receipt_mediatype` INT NOT NULL,
  PRIMARY KEY (`id_transaction_receipt`),
  INDEX `fk_transaction_receipt_transaction_receipt_mediatype1_idx` (`id_transaction_receipt_mediatype` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_receipt_transaction_receipt_mediatype1`
    FOREIGN KEY (`id_transaction_receipt_mediatype`)
    REFERENCES `mydb`.`transaction_receipt_mediatype` (`id_transaction_receipt_mediatype`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contact_info_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contact_info_type` (
  `id_contact_info_type` INT NOT NULL,
  `name` INT NOT NULL,
  PRIMARY KEY (`id_contact_info_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_contact_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_contact_info` (
  `id_users_contact_info` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(100) NOT NULL,
  `enabled` BIT(1) NOT NULL DEFAULT 1,
  `last_update` DATETIME NOT NULL DEFAULT NOW(),
  `id_user` INT NOT NULL,
  `id_contact_info_type` INT NOT NULL,
  PRIMARY KEY (`id_users_contact_info`),
  INDEX `fk_users_contact_info_users1_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_users_contact_info_contact_info_type1_idx` (`id_contact_info_type` ASC) VISIBLE,
  CONSTRAINT `fk_users_contact_info_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_contact_info_contact_info_type1`
    FOREIGN KEY (`id_contact_info_type`)
    REFERENCES `mydb`.`contact_info_type` (`id_contact_info_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pay_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pay_method` (
  `id_pay_method` INT NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `api_url` VARCHAR(200) NOT NULL,
  `secret_key` VARBINARY(255) NOT NULL,
  `key` VARCHAR(200) NOT NULL,
  `enabled` BIT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_pay_method`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`available_pay_methods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`available_pay_methods` (
  `id_available_pay_methods` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `token` VARCHAR(45) NOT NULL,
  `exp_token_date` DATETIME NOT NULL,
  `mask_account` VARCHAR(45) NULL,
  `callback_url` VARCHAR(45) NULL,
  `pay_method_id_pay_method` INT NOT NULL,
  `users_id_user` INT NOT NULL,
  PRIMARY KEY (`id_available_pay_methods`),
  INDEX `fk_available_pay_methods_pay_method1_idx` (`pay_method_id_pay_method` ASC) VISIBLE,
  INDEX `fk_available_pay_methods_users1_idx` (`users_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_available_pay_methods_pay_method1`
    FOREIGN KEY (`pay_method_id_pay_method`)
    REFERENCES `mydb`.`pay_method` (`id_pay_method`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_available_pay_methods_users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`currency` (
  `id_currency` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `acronym` VARCHAR(4) NOT NULL,
  `symbol` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id_currency`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payments` (
  `id_payments` INT NOT NULL,
  `amount` DECIMAL NOT NULL,
  `actual_amount` DECIMAL NOT NULL,
  `result` VARCHAR(200) NOT NULL,
  `auth` VARCHAR(45) NOT NULL,
  `reference` VARCHAR(45) NOT NULL,
  `change_token` VARBINARY(255) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `error` VARCHAR(4) NOT NULL,
  `date` DATETIME NOT NULL,
  `checksum` VARBINARY(255) NOT NULL,
  `id_user` INT NOT NULL,
  `id_available_pay_methods` INT NOT NULL,
  `id_pay_method` INT NOT NULL,
  `id_currency` INT NOT NULL,
  PRIMARY KEY (`id_payments`),
  INDEX `fk_payments_users1_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_payments_available_pay_methods1_idx` (`id_available_pay_methods` ASC) VISIBLE,
  INDEX `fk_payments_pay_method1_idx` (`id_pay_method` ASC) VISIBLE,
  INDEX `fk_payments_currency1_idx` (`id_currency` ASC) VISIBLE,
  CONSTRAINT `fk_payments_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_available_pay_methods1`
    FOREIGN KEY (`id_available_pay_methods`)
    REFERENCES `mydb`.`available_pay_methods` (`id_available_pay_methods`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_pay_method1`
    FOREIGN KEY (`id_pay_method`)
    REFERENCES `mydb`.`pay_method` (`id_pay_method`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_currency1`
    FOREIGN KEY (`id_currency`)
    REFERENCES `mydb`.`currency` (`id_currency`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notification_medium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notification_medium` (
  `id_notification_medium` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_notification_medium`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pay_notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pay_notification` (
  `id_notification` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `contrato` VARCHAR(45) NOT NULL,
  `montoactual` DECIMAL NOT NULL,
  `confirmation` BIT(1) NULL,
  `mensaje` VARCHAR(255) NOT NULL,
  `source` VARCHAR(45) NOT NULL,
  `destiny` VARCHAR(45) NOT NULL,
  `notification_status` VARCHAR(20) NOT NULL,
  `id_notification_medium` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_payments` INT NOT NULL,
  `id_users_contact_info` INT NOT NULL,
  PRIMARY KEY (`id_notification`),
  INDEX `fk_pay_notification_users_contact_info1_idx` (`id_users_contact_info` ASC) VISIBLE,
  INDEX `fk_pay_notification_payments1_idx` (`id_payments` ASC) VISIBLE,
  INDEX `fk_pay_notification_users1_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_pay_notification_notification_medium1_idx` (`id_notification_medium` ASC) VISIBLE,
  CONSTRAINT `fk_pay_notification_users_contact_info1`
    FOREIGN KEY (`id_users_contact_info`)
    REFERENCES `mydb`.`users_contact_info` (`id_users_contact_info`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pay_notification_payments1`
    FOREIGN KEY (`id_payments`)
    REFERENCES `mydb`.`payments` (`id_payments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pay_notification_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pay_notification_notification_medium1`
    FOREIGN KEY (`id_notification_medium`)
    REFERENCES `mydb`.`notification_medium` (`id_notification_medium`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trans_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trans_types` (
  `id_trans_types` INT NOT NULL AUTO_INCREMENT,
  `name` INT NOT NULL,
  PRIMARY KEY (`id_trans_types`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trans_sub_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trans_sub_types` (
  `id_trans_sub_types` INT NOT NULL AUTO_INCREMENT,
  `name` INT NOT NULL,
  PRIMARY KEY (`id_trans_sub_types`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_balance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_balance` (
  `id_user_balance` BIGINT(30) NOT NULL,
  `balance` DECIMAL NOT NULL,
  `last_balance` INT NOT NULL,
  `last_update` DATETIME NOT NULL DEFAULT NOW(),
  `checksum` VARBINARY(255) NOT NULL,
  `freeze_amount` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_currency` INT NOT NULL,
  PRIMARY KEY (`id_user_balance`),
  INDEX `fk_user_balance_pay_users1_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_user_balance_currency1_idx` (`id_currency` ASC) VISIBLE,
  CONSTRAINT `fk_user_balance_pay_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_balance_currency1`
    FOREIGN KEY (`id_currency`)
    REFERENCES `mydb`.`currency` (`id_currency`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exchange_rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exchange_rate` (
  `id_exchange_rate` INT NOT NULL AUTO_INCREMENT,
  `startdate` DATETIME NOT NULL,
  `enddate` DATETIME NOT NULL,
  `rate` DECIMAL NOT NULL,
  `enabled` BIT(1) NOT NULL DEFAULT 1,
  `current_exchange_rate` BIT(1) NOT NULL,
  `id_currency_s` INT NOT NULL,
  `id_currency_d` INT NOT NULL,
  PRIMARY KEY (`id_exchange_rate`),
  INDEX `fk_exchange_rate_currency1_idx` (`id_currency_s` ASC) VISIBLE,
  INDEX `fk_exchange_rate_currency2_idx` (`id_currency_d` ASC) VISIBLE,
  CONSTRAINT `fk_exchange_rate_currency1`
    FOREIGN KEY (`id_currency_s`)
    REFERENCES `mydb`.`currency` (`id_currency`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exchange_rate_currency2`
    FOREIGN KEY (`id_currency_d`)
    REFERENCES `mydb`.`currency` (`id_currency`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transactions` (
  `id_transaction` BIGINT(30) NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `datetime` DATETIME NOT NULL,
  `posttime` DATETIME NOT NULL,
  `transdatetime` DATETIME NOT NULL,
  `ref_number` VARCHAR(45) NULL,
  `checksum` VARBINARY(255) NOT NULL,
  `id_trans_types` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_trans_sub_types` INT NOT NULL,
  `id_user_balance` BIGINT(30) NOT NULL,
  `id_currency` INT NOT NULL,
  `id_exchange_rate` INT NOT NULL,
  `id_system` INT NOT NULL,
  `transaction_receipt_id_transaction_receipt` INT NOT NULL,
  `id_payments` INT NULL,
  PRIMARY KEY (`id_transaction`),
  INDEX `fk_transactions_trans_types1_idx` (`id_trans_types` ASC) VISIBLE,
  INDEX `fk_transactions_pay_users1_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_transactions_trans_sub_types1_idx` (`id_trans_sub_types` ASC) VISIBLE,
  INDEX `fk_transactions_user_balance1_idx` (`id_user_balance` ASC) VISIBLE,
  INDEX `fk_transactions_currency1_idx` (`id_currency` ASC) VISIBLE,
  INDEX `fk_transactions_exchange_rate1_idx` (`id_exchange_rate` ASC) VISIBLE,
  INDEX `fk_transactions_users1_idx` (`id_system` ASC) VISIBLE,
  INDEX `fk_transactions_transaction_receipt1_idx` (`transaction_receipt_id_transaction_receipt` ASC) VISIBLE,
  INDEX `fk_transactions_payments1_idx` (`id_payments` ASC) VISIBLE,
  CONSTRAINT `fk_transactions_trans_types1`
    FOREIGN KEY (`id_trans_types`)
    REFERENCES `mydb`.`trans_types` (`id_trans_types`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_pay_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_trans_sub_types1`
    FOREIGN KEY (`id_trans_sub_types`)
    REFERENCES `mydb`.`trans_sub_types` (`id_trans_sub_types`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_user_balance1`
    FOREIGN KEY (`id_user_balance`)
    REFERENCES `mydb`.`user_balance` (`id_user_balance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_currency1`
    FOREIGN KEY (`id_currency`)
    REFERENCES `mydb`.`currency` (`id_currency`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_exchange_rate1`
    FOREIGN KEY (`id_exchange_rate`)
    REFERENCES `mydb`.`exchange_rate` (`id_exchange_rate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_users1`
    FOREIGN KEY (`id_system`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_transaction_receipt1`
    FOREIGN KEY (`transaction_receipt_id_transaction_receipt`)
    REFERENCES `mydb`.`transaction_receipt` (`id_transaction_receipt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_payments1`
    FOREIGN KEY (`id_payments`)
    REFERENCES `mydb`.`payments` (`id_payments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plan_features`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plan_features` (
  `id_plan_features` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `enabled` BIT(1) NOT NULL DEFAULT 1,
  `datatype` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_plan_features`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`features_per_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`features_per_plan` (
  `id_features_per_plan` INT NOT NULL,
  `value` INT NOT NULL,
  `enabled` BIT(1) NOT NULL DEFAULT 1,
  `id_suscription` INT NOT NULL,
  `id_plan_features` INT NOT NULL,
  PRIMARY KEY (`id_features_per_plan`),
  INDEX `fk_features_per_plan_users_suscription1_idx` (`id_suscription` ASC) VISIBLE,
  INDEX `fk_features_per_plan_plan_features1_idx` (`id_plan_features` ASC) VISIBLE,
  CONSTRAINT `fk_features_per_plan_users_suscription1`
    FOREIGN KEY (`id_suscription`)
    REFERENCES `mydb`.`users_suscription` (`suscription_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_features_per_plan_plan_features1`
    FOREIGN KEY (`id_plan_features`)
    REFERENCES `mydb`.`plan_features` (`id_plan_features`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schedules` (
  `id_schedules` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `recurrency_type` VARCHAR(20) NOT NULL,
  `repeat` BIT(1) NOT NULL DEFAULT 0,
  `end_type` VARCHAR(45) NOT NULL,
  `repetitions` VARCHAR(45) NOT NULL,
  `end_date` DATETIME NULL,
  PRIMARY KEY (`id_schedules`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plan_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plan_person` (
  `id_plan_person` INT NOT NULL,
  `adquisition_date` DATETIME NOT NULL,
  `enabled` BIT(1) NOT NULL DEFAULT 1,
  `id_user` INT NOT NULL,
  `id_schedules` INT NOT NULL,
  PRIMARY KEY (`id_plan_person`),
  INDEX `fk_plan_person_users1_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_plan_person_schedules1_idx` (`id_schedules` ASC) VISIBLE,
  CONSTRAINT `fk_plan_person_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plan_person_schedules1`
    FOREIGN KEY (`id_schedules`)
    REFERENCES `mydb`.`schedules` (`id_schedules`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plan_prices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plan_prices` (
  `id_plan_prices` INT NOT NULL,
  `amount` INT NOT NULL,
  `recurrency_type` VARCHAR(20) NOT NULL,
  `posttime` DATETIME NOT NULL,
  `enddate` DATETIME NOT NULL,
  `current` BIT(1) NOT NULL,
  `id_user_suscription` INT NOT NULL,
  `id_plan_person` INT NOT NULL,
  PRIMARY KEY (`id_plan_prices`),
  INDEX `fk_plan_prices_users_suscription1_idx` (`id_user_suscription` ASC) VISIBLE,
  INDEX `fk_plan_prices_plan_person1_idx` (`id_plan_person` ASC) VISIBLE,
  CONSTRAINT `fk_plan_prices_users_suscription1`
    FOREIGN KEY (`id_user_suscription`)
    REFERENCES `mydb`.`users_suscription` (`suscription_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plan_prices_plan_person1`
    FOREIGN KEY (`id_plan_person`)
    REFERENCES `mydb`.`plan_person` (`id_plan_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schedule_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schedule_details` (
  `id_schedule_details` INT NOT NULL,
  `deleted` BIT(1) NOT NULL DEFAULT 0,
  `base_date` DATETIME NOT NULL,
  `date_part` DATETIME NOT NULL,
  `last_execution` DATETIME NOT NULL,
  `next_execution` DATETIME NOT NULL,
  `id_schedules` INT NOT NULL,
  PRIMARY KEY (`id_schedule_details`),
  INDEX `fk_schedule_details_schedules1_idx` (`id_schedules` ASC) VISIBLE,
  CONSTRAINT `fk_schedule_details_schedules1`
    FOREIGN KEY (`id_schedules`)
    REFERENCES `mydb`.`schedules` (`id_schedules`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_permissions` (
  `id_user_permissions` INT NOT NULL,
  `enabled` BIT(1) NOT NULL DEFAULT 1,
  `deleted` BIT(1) NOT NULL DEFAULT 0,
  `last_update` DATETIME NOT NULL DEFAULT NOW(),
  `user_name` VARCHAR(45) NOT NULL,
  `checksum` VARBINARY(255) NOT NULL,
  `id_permission` INT NOT NULL,
  PRIMARY KEY (`id_user_permissions`),
  INDEX `fk_user_permissions_permissions1_idx` (`id_permission` ASC) VISIBLE,
  CONSTRAINT `fk_user_permissions_permissions1`
    FOREIGN KEY (`id_permission`)
    REFERENCES `mydb`.`permissions` (`id_permission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person_plan_limits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person_plan_limits` (
  `id_person_plan_limits` INT NOT NULL,
  `limit` INT NOT NULL,
  `id_plan_features` INT NOT NULL,
  `id_plan_person` INT NOT NULL,
  PRIMARY KEY (`id_person_plan_limits`),
  INDEX `fk_person_plan_limits_plan_features1_idx` (`id_plan_features` ASC) VISIBLE,
  INDEX `fk_person_plan_limits_plan_person1_idx` (`id_plan_person` ASC) VISIBLE,
  CONSTRAINT `fk_person_plan_limits_plan_features1`
    FOREIGN KEY (`id_plan_features`)
    REFERENCES `mydb`.`plan_features` (`id_plan_features`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_plan_limits_plan_person1`
    FOREIGN KEY (`id_plan_person`)
    REFERENCES `mydb`.`plan_person` (`id_plan_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`translations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`translations` (
  `id_translations` INT NOT NULL,
  `code` VARCHAR(20) NOT NULL,
  `caption` VARCHAR(200) NOT NULL,
  `enabled` BIT(1) NOT NULL DEFAULT 1,
  `id_language` INT NOT NULL,
  PRIMARY KEY (`id_translations`),
  INDEX `fk_translations_languages1_idx` (`id_language` ASC) VISIBLE,
  CONSTRAINT `fk_translations_languages1`
    FOREIGN KEY (`id_language`)
    REFERENCES `mydb`.`languages` (`id_language`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`log_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`log_types` (
  `id_log_type` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `ref_1_des` VARCHAR(45) NULL,
  `ref_2_des` VARCHAR(45) NULL,
  `val_1_des` VARCHAR(45) NULL,
  `val_2_des` VARCHAR(45) NULL,
  PRIMARY KEY (`id_log_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`log_sources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`log_sources` (
  `id_log_source` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_log_source`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`log_severities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`log_severities` (
  `id_log_severity` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_log_severity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`logs` (
  `id_logs` INT NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `posttime` DATETIME NOT NULL,
  `computer` VARCHAR(45) NOT NULL,
  `user_name` VARCHAR(120) NOT NULL,
  `trace` VARCHAR(45) NOT NULL,
  `reference_id_1` BIGINT(8) NULL,
  `reference_id_2` BIGINT(8) NULL,
  `value_1` VARCHAR(180) NULL,
  `value_2` VARCHAR(180) NULL,
  `checksum` VARBINARY(200) NOT NULL,
  `id_log_type` INT NOT NULL,
  `id_log_source` INT NOT NULL,
  `id_log_severity` INT NOT NULL,
  PRIMARY KEY (`id_logs`),
  INDEX `fk_logs_log_types1_idx` (`id_log_type` ASC) VISIBLE,
  INDEX `fk_logs_log_sources1_idx` (`id_log_source` ASC) VISIBLE,
  INDEX `fk_logs_log_severities1_idx` (`id_log_severity` ASC) VISIBLE,
  CONSTRAINT `fk_logs_log_types1`
    FOREIGN KEY (`id_log_type`)
    REFERENCES `mydb`.`log_types` (`id_log_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logs_log_sources1`
    FOREIGN KEY (`id_log_source`)
    REFERENCES `mydb`.`log_sources` (`id_log_source`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logs_log_severities1`
    FOREIGN KEY (`id_log_severity`)
    REFERENCES `mydb`.`log_severities` (`id_log_severity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`audio_recordings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`audio_recordings` (
  `audio_recording_id` INT NOT NULL AUTO_INCREMENT,
  `audio_path` VARCHAR(200) NOT NULL,
  `upload_date` DATETIME NOT NULL,
  `deleted` BIT(1) NOT NULL DEFAULT 0,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`audio_recording_id`),
  UNIQUE INDEX `audio_upload_id_UNIQUE` (`audio_recording_id` ASC) VISIBLE,
  INDEX `fk_audio_uploads_users1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_audio_uploads_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transcription_configurations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transcription_configurations` (
  `trans_conf_id` INT NOT NULL,
  `media_enc` VARCHAR(50) NOT NULL,
  `sample_rate` INT NOT NULL,
  `language_code` VARCHAR(10) NULL,
  `identify_language` BIT(1) NOT NULL DEFAULT 1,
  `identify_multiple_languages` BIT(1) NOT NULL DEFAULT 1,
  `jsonConfig` JSON NOT NULL,
  `audio_recording_id` INT NOT NULL,
  PRIMARY KEY (`trans_conf_id`),
  UNIQUE INDEX `trans_conf_id_UNIQUE` (`trans_conf_id` ASC) VISIBLE,
  INDEX `fk_transcription_configurations_audio_uploads1_idx` (`audio_recording_id` ASC) VISIBLE,
  CONSTRAINT `fk_transcription_configurations_audio_uploads1`
    FOREIGN KEY (`audio_recording_id`)
    REFERENCES `mydb`.`audio_recordings` (`audio_recording_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transcriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transcriptions` (
  `transcription_id` INT NOT NULL AUTO_INCREMENT,
  `start_time` FLOAT NOT NULL,
  `end_time` FLOAT NOT NULL,
  `is_partial` BIT(1) NOT NULL,
  `result_ID` VARCHAR(50) NOT NULL,
  `trans_conf_id` INT NOT NULL,
  PRIMARY KEY (`transcription_id`),
  UNIQUE INDEX `transcription_id_UNIQUE` (`transcription_id` ASC) VISIBLE,
  INDEX `fk_transcriptions_transcription_configurations1_idx` (`trans_conf_id` ASC) VISIBLE,
  UNIQUE INDEX `result_ID_UNIQUE` (`result_ID` ASC) VISIBLE,
  CONSTRAINT `fk_transcriptions_transcription_configurations1`
    FOREIGN KEY (`trans_conf_id`)
    REFERENCES `mydb`.`transcription_configurations` (`trans_conf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transcription_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transcription_items` (
  `trans_item_id` INT NOT NULL AUTO_INCREMENT,
  `transcription_id` INT NOT NULL,
  `content` TEXT NOT NULL,
  `start_time` FLOAT NOT NULL,
  `end_time` FLOAT NOT NULL,
  `stable` BIT(1) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `vocabulary_filter_match` BIT(1) NOT NULL,
  PRIMARY KEY (`trans_item_id`),
  INDEX `fk_transcription_items_transcriptions1_idx` (`transcription_id` ASC) VISIBLE,
  UNIQUE INDEX `trans_item_id_UNIQUE` (`trans_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_transcription_items_transcriptions1`
    FOREIGN KEY (`transcription_id`)
    REFERENCES `mydb`.`transcriptions` (`transcription_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ai_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ai_sessions` (
  `session_id` INT NOT NULL AUTO_INCREMENT,
  `session_uuid` VARCHAR(50) NOT NULL,
  `bot_id` VARCHAR(50) NOT NULL,
  `bot_alias_id` VARCHAR(50) NOT NULL,
  `start_time` DATETIME NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`session_id`),
  UNIQUE INDEX `ai_sessions_id_UNIQUE` (`session_id` ASC) VISIBLE,
  INDEX `fk_ai_sessions_users1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_ai_sessions_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_tactile_feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_tactile_feedback` (
  `feedback_id` INT NOT NULL AUTO_INCREMENT,
  `event_type` VARCHAR(45) NOT NULL,
  `button_pressed` VARCHAR(45) NULL,
  `touch_duration` DECIMAL NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `session_id` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`feedback_id`),
  INDEX `fk_user_tactile_feedback_ai_sessions1_idx` (`session_id` ASC) VISIBLE,
  INDEX `fk_user_tactile_feedback_users1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_tactile_feedback_ai_sessions1`
    FOREIGN KEY (`session_id`)
    REFERENCES `mydb`.`ai_sessions` (`session_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_tactile_feedback_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ai_requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ai_requests` (
  `request_id` INT NOT NULL AUTO_INCREMENT,
  `input_mode` ENUM("Text", "Audio") NOT NULL,
  `text_content` TEXT NULL,
  `audio_recording` BLOB NULL,
  `content_type` VARCHAR(50) NULL,
  `jsonConfig` JSON NOT NULL,
  `session_id` INT NOT NULL,
  `transcription_id` INT NULL,
  `audio_recording_id` INT NULL,
  `feedback_id` INT NULL,
  PRIMARY KEY (`request_id`),
  UNIQUE INDEX `request_id_UNIQUE` (`request_id` ASC) VISIBLE,
  INDEX `fk_lex_requests_ai_sessions1_idx` (`session_id` ASC) VISIBLE,
  INDEX `fk_lex_requests_transcriptions1_idx` (`transcription_id` ASC) VISIBLE,
  INDEX `fk_lex_requests_audio_recordings1_idx` (`audio_recording_id` ASC) VISIBLE,
  INDEX `fk_ai_requests_user_tactile_feedback1_idx` (`feedback_id` ASC) VISIBLE,
  CONSTRAINT `fk_lex_requests_ai_sessions1`
    FOREIGN KEY (`session_id`)
    REFERENCES `mydb`.`ai_sessions` (`session_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lex_requests_transcriptions1`
    FOREIGN KEY (`transcription_id`)
    REFERENCES `mydb`.`transcriptions` (`transcription_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lex_requests_audio_recordings1`
    FOREIGN KEY (`audio_recording_id`)
    REFERENCES `mydb`.`audio_recordings` (`audio_recording_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ai_requests_user_tactile_feedback1`
    FOREIGN KEY (`feedback_id`)
    REFERENCES `mydb`.`user_tactile_feedback` (`feedback_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ai_intents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ai_intents` (
  `intent_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `confirmation_state` VARCHAR(50) NULL,
  `state` VARCHAR(50) NULL,
  `confidence` DECIMAL NULL,
  `user_confirmation` BIT(1) NOT NULL DEFAULT 0,
  `timestamp` DATETIME NOT NULL,
  `session_id` INT NOT NULL,
  `request_id` INT NOT NULL,
  PRIMARY KEY (`intent_id`),
  INDEX `fk_ai_intents_ai_sessions1_idx` (`session_id` ASC) VISIBLE,
  INDEX `fk_ai_intents_lex_requests1_idx` (`request_id` ASC) VISIBLE,
  CONSTRAINT `fk_ai_intents_ai_sessions1`
    FOREIGN KEY (`session_id`)
    REFERENCES `mydb`.`ai_sessions` (`session_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ai_intents_lex_requests1`
    FOREIGN KEY (`request_id`)
    REFERENCES `mydb`.`ai_requests` (`request_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entity_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entity_type` (
  `entity_type_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`entity_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recognized_entities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recognized_entities` (
  `entity_id` INT NOT NULL AUTO_INCREMENT,
  `entity_name` VARCHAR(100) NOT NULL,
  `entity_value` TEXT NOT NULL,
  `session_id` INT NOT NULL,
  `intent_id` INT NOT NULL,
  `entity_type_id` INT NOT NULL,
  PRIMARY KEY (`entity_id`),
  INDEX `fk_recognized_entities_ai_sessions1_idx` (`session_id` ASC) VISIBLE,
  INDEX `fk_recognized_entities_ai_intents1_idx` (`intent_id` ASC) VISIBLE,
  INDEX `fk_recognized_entities_entity_type1_idx` (`entity_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_recognized_entities_ai_sessions1`
    FOREIGN KEY (`session_id`)
    REFERENCES `mydb`.`ai_sessions` (`session_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recognized_entities_ai_intents1`
    FOREIGN KEY (`intent_id`)
    REFERENCES `mydb`.`ai_intents` (`intent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recognized_entities_entity_type1`
    FOREIGN KEY (`entity_type_id`)
    REFERENCES `mydb`.`entity_type` (`entity_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`responses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`responses` (
  `response_id` INT NOT NULL AUTO_INCREMENT,
  `content_type` VARCHAR(100) NOT NULL,
  `content` TEXT NULL,
  `audio_data` BLOB NULL,
  `timestamp` DATETIME NOT NULL,
  `session_id` INT NOT NULL,
  `request_id` INT NOT NULL,
  PRIMARY KEY (`response_id`),
  INDEX `fk_responses_ai_sessions1_idx` (`session_id` ASC) VISIBLE,
  INDEX `fk_responses_lex_requests1_idx` (`request_id` ASC) VISIBLE,
  CONSTRAINT `fk_responses_ai_sessions1`
    FOREIGN KEY (`session_id`)
    REFERENCES `mydb`.`ai_sessions` (`session_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_responses_lex_requests1`
    FOREIGN KEY (`request_id`)
    REFERENCES `mydb`.`ai_requests` (`request_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`error_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`error_types` (
  `error_type_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`error_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ai_errors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ai_errors` (
  `error_id` INT NOT NULL AUTO_INCREMENT,
  `confidence` DECIMAL NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `occurrence_count` INT NOT NULL,
  `error_type_id` INT NOT NULL,
  `session_id` INT NOT NULL,
  PRIMARY KEY (`error_id`),
  INDEX `fk_ai_errors_error_types1_idx` (`error_type_id` ASC) VISIBLE,
  INDEX `fk_ai_errors_ai_sessions1_idx` (`session_id` ASC) VISIBLE,
  CONSTRAINT `fk_ai_errors_error_types1`
    FOREIGN KEY (`error_type_id`)
    REFERENCES `mydb`.`error_types` (`error_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ai_errors_ai_sessions1`
    FOREIGN KEY (`session_id`)
    REFERENCES `mydb`.`ai_sessions` (`session_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ai_commands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ai_commands` (
  `command_id` INT NOT NULL,
  `command_name` VARCHAR(20) NOT NULL,
  `command_description` VARCHAR(150) NOT NULL,
  `command` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`command_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ai_abandonments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ai_abandonments` (
  `abandonment_id` INT NOT NULL AUTO_INCREMENT,
  `reason` TEXT NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `request_id` INT NOT NULL,
  `session_id` INT NOT NULL,
  PRIMARY KEY (`abandonment_id`),
  INDEX `fk_ai_abandonments_ai_requests1_idx` (`request_id` ASC) VISIBLE,
  INDEX `fk_ai_abandonments_ai_sessions1_idx` (`session_id` ASC) VISIBLE,
  CONSTRAINT `fk_ai_abandonments_ai_requests1`
    FOREIGN KEY (`request_id`)
    REFERENCES `mydb`.`ai_requests` (`request_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ai_abandonments_ai_sessions1`
    FOREIGN KEY (`session_id`)
    REFERENCES `mydb`.`ai_sessions` (`session_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ai_corrections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ai_corrections` (
  `correction_id` INT NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `ori_request_id` INT NULL,
  `corr_request_id` INT NULL,
  `ori_response_id` INT NULL,
  `corr_response_id` INT NULL,
  PRIMARY KEY (`correction_id`),
  INDEX `fk_ai_corrections_ai_requests1_idx` (`ori_request_id` ASC) VISIBLE,
  INDEX `fk_ai_corrections_ai_requests2_idx` (`corr_request_id` ASC) VISIBLE,
  INDEX `fk_ai_corrections_responses1_idx` (`ori_response_id` ASC) VISIBLE,
  INDEX `fk_ai_corrections_responses2_idx` (`corr_response_id` ASC) VISIBLE,
  CONSTRAINT `fk_ai_corrections_ai_requests1`
    FOREIGN KEY (`ori_request_id`)
    REFERENCES `mydb`.`ai_requests` (`request_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ai_corrections_ai_requests2`
    FOREIGN KEY (`corr_request_id`)
    REFERENCES `mydb`.`ai_requests` (`request_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ai_corrections_responses1`
    FOREIGN KEY (`ori_response_id`)
    REFERENCES `mydb`.`responses` (`response_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ai_corrections_responses2`
    FOREIGN KEY (`corr_response_id`)
    REFERENCES `mydb`.`responses` (`response_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ai_actions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ai_actions` (
  `action_id` INT NOT NULL,
  `action_text` TEXT NOT NULL,
  `confidence` DECIMAL NOT NULL,
  `confirmation` BIT(1) NOT NULL DEFAULT 0,
  `jsonPayConfig` JSON NOT NULL,
  `execution_status` VARCHAR(45) NOT NULL,
  `executed_at` DATETIME NOT NULL,
  `execution_time` DECIMAL NULL,
  `command_id` INT NOT NULL,
  `session_id` INT NOT NULL,
  `intent_id` INT NOT NULL,
  `request_id` INT NOT NULL,
  PRIMARY KEY (`action_id`),
  INDEX `fk_ai_actions_ai_commands1_idx` (`command_id` ASC) VISIBLE,
  INDEX `fk_ai_actions_ai_sessions1_idx` (`session_id` ASC) VISIBLE,
  INDEX `fk_ai_actions_ai_intents1_idx` (`intent_id` ASC) VISIBLE,
  INDEX `fk_ai_actions_ai_requests1_idx` (`request_id` ASC) VISIBLE,
  CONSTRAINT `fk_ai_actions_ai_commands1`
    FOREIGN KEY (`command_id`)
    REFERENCES `mydb`.`ai_commands` (`command_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ai_actions_ai_sessions1`
    FOREIGN KEY (`session_id`)
    REFERENCES `mydb`.`ai_sessions` (`session_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ai_actions_ai_intents1`
    FOREIGN KEY (`intent_id`)
    REFERENCES `mydb`.`ai_intents` (`intent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ai_actions_ai_requests1`
    FOREIGN KEY (`request_id`)
    REFERENCES `mydb`.`ai_requests` (`request_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
